### ISSUE TITLE
Preview builds failing

### ISSUE THREAD

**Issue by ro-savage** [NAVCoin/navcoin-org#14]
Most (All?) preview builds are failing this this error.
Production builds seem to work though.

```
1:08:00 AM: Building sites …
1:08:00 AM: 
Total in 192 ms
1:08:00 AM: Error: Error building site: Prepare pages failed: ["template: __c437eafebe15ae09e478a836a37c6edc:1060: unexpected \"&\" in command"]…
```

**Comment by craigmacgregor** [comment]
Master branch build is also failing on this now. From what I understand this error comes up when there is an undefined variable being used somewhere in the templates. It's a real pain in the ass to find out where it is coming from though, the error sucks and can't be replicated locally for some reason. We do need to figure this out because its blocking deploys.

**Comment by rsh52** [comment]
Was this ever solved? I find this happens when building extremely randomly.
